name: Check pull request
run-name: Build on pull request, branch '${{ github.head_ref }}'

on:
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: check-pull-request-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  validate:
    name: Check
    uses: ./.github/workflows/sub-check.yml
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.1', '8.2', '8.3', '8.4', '8.5' ]
    with:
      PHP_VERSION: ${{ matrix.php-version }}