name: Update copyright years

on:
  schedule:
    - cron: '0 10 1 1 *'  # 10:00 AM on January 1
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:

  update-copyright-years:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commitTitle: 'Update copyright years'
          transform: (?<=Copyright Â© )(?<from>\d{4})?[-]?(\d{4})
          path: |
            public/index.php
          labels: 'T: Maintenance'
